######################### default configuration ###############################
baseURL = "https://www.lampreyusa.com"
title = "Lamprey Security Solutions"
theme = "biztrox-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "biztrox" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = "Fr" # desable language from here

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick-theme.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


#################################### navigation ##################################
[menu]
    
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Service"
  URL = "service"
  weight = 2
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3
  
   [[menu.main]]
   name = "Team"
   URL = "team"
   weight = 4
  
  [[menu.main]]
  name = "Pricing"
  URL = "pricing"
  weight = 5
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6

  [[menu.main]]
  weight = 7
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Project"
    URL = "project"

  # footer menu 
  
  [[menu.footer]]
  name = "Privacy Policy"
  URL = "/pages/privacy/"
  weight = 1
  
  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "/pages/conditions/"
  weight = 2


########################### default parameters #################################
[params]
logo = "images/logo.png"
logo_white = "images/logo-footer.png"
mail = "info@lampreyusa.com"
mobile = "+1 786 609-4316‬"
# Meta data
description = "Many companies trust us. We will create a custom security solution for you. Equipment installation offers. Chat with a business solutions expert now."
author = "Lamprey"
# contact form
contact_form_action = "https://formspree.io/xnqgjoeb"
# method="POST"
# Google Analitycs
google_analitycs_id = "UA-167186903-1"

# mailchimp subsciption
mailchimp_form_action = "https://lampreyusa.us18.list-manage.com/subscribe/post?u=fcfdcc4a9ce78cb5efcfb644d&amp;id=7c91641655" # replace this url with yours
mailchimp_form_name = "b_fcfdcc4a9ce78cb5efcfb644d_7c91641655" # replace this code with yours

# nav Button
[params.nav_button]
enable = true
link = "contact"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif"

############################ Contact information ############################
[[params.contacts]]
icon = "ti-mobile"

  [[params.contacts.contact]]
  contact_item = "+1 786 609 4316‬"


[[params.contacts]]
icon = "ti-email"

  [[params.contacts.contact]]
  contact_item = "info@lampreyusa.com"

  
[[params.contacts]]
icon = "ti-map-alt"

  [[params.contacts.contact]]
  contact_item = "8600 NW ST #6 DORAL"

  [[params.contacts.contact]]
  contact_item = "MIAMI, FL 33166"

############################ google map #####################################
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "25.8311002"
map_longitude = "-80.3372163"
map_marker = "images/marker.png"

############################ client logo slider #############################
[[params.clients_logo_slider]]
logo = "images/client-logo/avigilon.png"
link = "https://www.avigilon.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/bosch.png"
link = "https://www.boschsecurity.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/dahua.png"
link = "https://www.dahuasecurity.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/epcom.png"
link = "https://epcom.net"

[[params.clients_logo_slider]]
logo = "images/client-logo/hikvision.png"
link = "https://www.hikvision.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/linksys.png"
link = "https://www.linksys.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/ubiquiti.png"
link = "https://www.ui.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/nest.png"
link = "https://www.nest.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/panasonic.png"
link = "https://www.panasonic.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/netgear.png"
link = "https://www.netgear.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/axis.png"
link = "https://www.axis.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/uniden.png"
link = "https://uniden.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/cisco.png"
link = "https://cisco.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/grandstream.png"
link = "https://pelco.com/"

[[params.clients_logo_slider]]
logo = "images/client-logo/pelco.png"
link = "http://www.grandstream.com/"




########################### social icon #####################################
[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/lampreyllc/"

[[params.social]]
icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://vimeo.com/user118095291"

[[params.social]]
icon = "ti-email" # themify icon pack : https://themify.me/themify-icons
link = "https://www.lampreyusa.com/contact/"



[Languages]
  
  ################################### English language #####################################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 1
  home = "Home"

  # footer
  [Languages.en.params.footer]
  content = "Connect with us through social media. Follow Lamprey on social media to keep up-to-date with the latest company news"
  # subscribe
  subscribe = "Newsletter"
  subscribe_content = "Subscribe to our newsletter and stay updated with our latest offers."

  # copyright
  copyright = "Copyright &copy; 2020 by Lamprey LLC "



################################ Franch language ################################
  [Languages.fr]
  languageName = "Fr"
  languageCode = "fr-fr"
  contentDir = "content/french"
  weight = 2
  home = "Accueil"

  # footer
  [Languages.fr.params.footer]
  content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."

  # subscribe
  subscribe = "Subscribe Us"
  subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

  # copyright
  copyright = "Copyright &copy; 2019 a hugo theme by [themefisher.com](https://themefisher.com)"
